/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*Saya Aldi Saepurahman mengerjakan evaluasi Tugas Praktikum 2 dalam mata kuliah
Desain dan Pemrograman Berorientasi Objek untuk keberkahanNya maka saya tidak
melakukan kecurangan seperti yang telah dispesifikasikan. Aamiin.*/
package tp2pbo2021;
/*import semua class seperti Connection, ResultSet, SQLException, Statement
untuk melakukan koneksi ke database, dan eksekusi query yang diminta/
Import juga class Arraylist untuk menampung data dari database, JOptionPane
untuk menampilkan pesan error atau sukses dan DTM untuk class table*/
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aldi Saepurahman
 */
public class TP2 extends javax.swing.JFrame {

    /**
     * Creates new form TP2
     */
    //deklarasi variabel khusus di Form seperti koneksi, arraylist, header, dan model tabel
    private Connection koneksi;
    private ArrayList<Mobil> listMobil;
    private String header[] = new String[]{"No", "Merk", "Plat", "Warna", "Jenis"};
    private DefaultTableModel dtm;
    
    public TP2() {
        //desain elemen form
        initComponents();
        //buat koneksi ke database
        koneksi = connect("localhost", "3306", "root", "", "tp2pbo2021");
        //instansiasi list dan model tabel
        listMobil = new ArrayList<>();
        dtm = new DefaultTableModel(header, 0);
        jTableMobil.setModel(dtm);
        this.setLocationRelativeTo(null);
        //set visibilitas panel halaman utama dan hilangkan panel lain dari layar
        jPanelInfo.setVisible(false);
        jPanelTable.setVisible(false);
        jPanelForm.setVisible(false);
        jPanelWelcome.setVisible(true);
    }
    
    //buat fungsi koneksi ke database
    public static Connection connect(String host, String port, 
            String username, String password, String db){
        //buat koneksinya dengan library jdbc mysql
        String conn = "jdbc:mysql://"+ host + ":" + port + "/" + db;
        Connection koneksi;
        //coba untuk koneksi ke database
        try{
            //ambil library mysql
            Class.forName("com.mysql.cj.jdbc.Driver");
            //tes koneksinya
            koneksi = DriverManager.getConnection(conn, username, password);
        }catch(Exception ex){
            //jika koneksi gagal, tampilkan pesan error dan set koneksi dengan null
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Koneksi Error");
            koneksi = null;
        }
        //kembalikan koneksi
        return koneksi;
        
    }
    
    //buat prosedur mengambil data mobil dari database
    public void getMobil(){
        //try and catch karena ini diperlukan untuk mengecek koneksi database
        try{
            //buat koneksi sebelum mengeksekusi query
            Statement stmt = koneksi.createStatement();
            //ambil data mobil dari database
            String query = "SELECT * FROM mobil";
            //eksekusi querynya
            ResultSet rs = stmt.executeQuery(query);
            //lakukan perulangan selama ada data dari database
            while(rs.next()){
                //masukkan kedalam list Mobil
                listMobil.add(new Mobil(
                        rs.getString("merk"), rs.getString("plat"),
                        rs.getString("warna"), rs.getString("jenis")));
            }
        }catch(SQLException ex){
            //yang dilakukan bila koneksi gagal
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Error Saudara-Saudara!");
        }
    }
    
    //buat prosedur menampilkan data dari database
    public void printMobil(){
        //ambil data dari database
        getMobil();
        //reset data dari table
        dtm.setRowCount(0);
        //tampilkan datanya pada table
        for (int i = 0; i < listMobil.size(); i++) {
            Object[] objs = {i+1, listMobil.get(i).getMerk(),
                listMobil.get(i).getPlat(), listMobil.get(i).getWarna(),
                listMobil.get(i).getJenis()};
            dtm.addRow(objs);
        }
        //hapus isi listMobil untuk mereset ulang hasilquery ketika dipanggil kembali
        listMobil.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNav = new javax.swing.JPanel();
        jLabelForm = new javax.swing.JLabel();
        jLabelTable = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelJudul = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanelWelcome = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabelNama = new javax.swing.JLabel();
        jLabelNim = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jPanelTable = new javax.swing.JPanel();
        jScrollPaneMobil = new javax.swing.JScrollPane();
        jTableMobil = new javax.swing.JTable();
        jPanelForm = new javax.swing.JPanel();
        jLabelTitleForm = new javax.swing.JLabel();
        jLabelMerk = new javax.swing.JLabel();
        jTextFieldMerk = new javax.swing.JTextField();
        jLabelPlat = new javax.swing.JLabel();
        jTextFieldPlat = new javax.swing.JTextField();
        jLabelWarna = new javax.swing.JLabel();
        jTextFieldWarna = new javax.swing.JTextField();
        jLabelJenis = new javax.swing.JLabel();
        jComboBoxJenis = new javax.swing.JComboBox<>();
        jButtonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelNav.setBackground(new java.awt.Color(255, 102, 0));

        jLabelForm.setFont(new java.awt.Font("Mont SemiBold", 0, 18)); // NOI18N
        jLabelForm.setForeground(new java.awt.Color(255, 255, 255));
        jLabelForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelForm.setText("FORM");
        jLabelForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFormMouseClicked(evt);
            }
        });

        jLabelTable.setFont(new java.awt.Font("Mont SemiBold", 0, 18)); // NOI18N
        jLabelTable.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTable.setText("TABLE");
        jLabelTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTableMouseClicked(evt);
            }
        });

        jLabelInfo.setFont(new java.awt.Font("Mont SemiBold", 0, 18)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("INFO");
        jLabelInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoMouseClicked(evt);
            }
        });

        jLabelJudul.setFont(new java.awt.Font("Mont SemiBold", 0, 20)); // NOI18N
        jLabelJudul.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJudul.setText("DATA MOBIL");
        jLabelJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelNavLayout = new javax.swing.GroupLayout(jPanelNav);
        jPanelNav.setLayout(jPanelNavLayout);
        jPanelNavLayout.setHorizontalGroup(
            jPanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelForm)
                .addGap(32, 32, 32)
                .addComponent(jLabelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelNavLayout.setVerticalGroup(
            jPanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelForm)
                    .addComponent(jLabelTable)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabelWelcome.setFont(new java.awt.Font("Mont Light", 1, 24)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("WELCOME!!");

        javax.swing.GroupLayout jPanelWelcomeLayout = new javax.swing.GroupLayout(jPanelWelcome);
        jPanelWelcome.setLayout(jPanelWelcomeLayout);
        jPanelWelcomeLayout.setHorizontalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWelcomeLayout.setVerticalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelInfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNama.setFont(new java.awt.Font("Mont Light", 1, 20)); // NOI18N
        jLabelNama.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNama.setText("ALDI SAEPURAHMAN");

        jLabelNim.setFont(new java.awt.Font("Mont Light", 1, 20)); // NOI18N
        jLabelNim.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNim.setText("1901942");

        jLabelPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2pbo2021/aldi.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNama, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jLabelNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabelPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabelNama)
                .addGap(18, 18, 18)
                .addComponent(jLabelNim)
                .addGap(157, 157, 157))
        );

        jPanelTable.setBackground(new java.awt.Color(255, 255, 255));

        jTableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Merk", "Plat", "Warna", "Jenis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMobil.getTableHeader().setResizingAllowed(false);
        jScrollPaneMobil.setViewportView(jTableMobil);
        if (jTableMobil.getColumnModel().getColumnCount() > 0) {
            jTableMobil.getColumnModel().getColumn(0).setResizable(false);
            jTableMobil.getColumnModel().getColumn(1).setResizable(false);
            jTableMobil.getColumnModel().getColumn(2).setResizable(false);
            jTableMobil.getColumnModel().getColumn(3).setResizable(false);
            jTableMobil.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTableLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPaneMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTableLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPaneMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitleForm.setFont(new java.awt.Font("Mont SemiBold", 1, 18)); // NOI18N
        jLabelTitleForm.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitleForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleForm.setText("FORM MOBIL");

        jLabelMerk.setFont(new java.awt.Font("Mont SemiBold", 1, 18)); // NOI18N
        jLabelMerk.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMerk.setText("Merk");

        jLabelPlat.setFont(new java.awt.Font("Mont SemiBold", 1, 18)); // NOI18N
        jLabelPlat.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPlat.setText("Plat");

        jLabelWarna.setFont(new java.awt.Font("Mont SemiBold", 1, 18)); // NOI18N
        jLabelWarna.setForeground(new java.awt.Color(0, 0, 0));
        jLabelWarna.setText("Warna");

        jLabelJenis.setFont(new java.awt.Font("Mont SemiBold", 1, 18)); // NOI18N
        jLabelJenis.setForeground(new java.awt.Color(0, 0, 0));
        jLabelJenis.setText("Jenis");

        jComboBoxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biasa", "Balap", "Sport", "Truk" }));

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubmitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitleForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMerk)
                            .addComponent(jLabelPlat)
                            .addComponent(jLabelWarna)
                            .addComponent(jLabelJenis))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMerk)
                            .addComponent(jTextFieldPlat)
                            .addComponent(jTextFieldWarna)
                            .addComponent(jComboBoxJenis, 0, 220, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTitleForm)
                .addGap(37, 37, 37)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMerk)
                    .addComponent(jTextFieldMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlat)
                    .addComponent(jTextFieldPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWarna)
                    .addComponent(jTextFieldWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJenis)
                    .addComponent(jComboBoxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWelcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //aksi label info ketika ditekan
    private void jLabelInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoMouseClicked
        //tampilkan panel info yang berisi data diri
        jPanelInfo.setVisible(true);
        jPanelWelcome.setVisible(false);
        jPanelTable.setVisible(false);
        jPanelForm.setVisible(false);
    }//GEN-LAST:event_jLabelInfoMouseClicked
    
    //aksi label table ketika ditekan
    private void jLabelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTableMouseClicked
        //panggil prosedur printMobil untuk menampilkan data mobil dari database
        printMobil();
        //tampilkan panel table yang berisi data mobil dari database
        jPanelInfo.setVisible(false);
        jPanelWelcome.setVisible(false);
        jPanelTable.setVisible(true);
        jPanelForm.setVisible(false);
    }//GEN-LAST:event_jLabelTableMouseClicked
    
    //aksi label form ketika ditekan
    private void jLabelFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFormMouseClicked
        //tampilkan panel form untuk menambah data mobil dan hilangkan label info dan table
        jPanelInfo.setVisible(false);
        jPanelWelcome.setVisible(false);
        jPanelTable.setVisible(false);
        jPanelForm.setVisible(true);
        jLabelInfo.setVisible(false);
        jLabelTable.setVisible(false);
    }//GEN-LAST:event_jLabelFormMouseClicked
    
    //aksi tombol submit ketika diklik
    private void jButtonSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubmitMouseClicked
        //ambil data inputan dan simpan kedalam variabel
        String merk = jTextFieldMerk.getText();
	String plat = jTextFieldPlat.getText();
        String warna = jTextFieldWarna.getText();
        String jenis = jComboBoxJenis.getSelectedItem().toString();
        //jika data yang diisi lengkap
        if (!warna.isEmpty() && !plat.isEmpty() && !merk.isEmpty()){
            //try and catch untuk insert data
            try{
                //buat koneksi untuk eksekusi query
                Statement stmt = koneksi.createStatement();
                //buat query insert data mobil
                String query = "INSERT INTO mobil (plat, merk, warna, jenis) "
                        + "VALUES ("
                        + "'"+ plat +"','"+ merk +"','"+ warna + "','"+ jenis + "')";
                //tampung status eksekusi querynya
                int sukses = stmt.executeUpdate(query);
                //jika status nya sukses
                if (sukses == 1) {
                    //tampilkan pesan sukses
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan",
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    //kosongkan data dari table
                    jTextFieldMerk.setText("");
                    jTextFieldPlat.setText("");
                    jTextFieldWarna.setText("");
                    jComboBoxJenis.setSelectedIndex(0);
                    //tampilkan kembali label info dan table
                    jLabelTable.setVisible(true);
                    jLabelInfo.setVisible(true);
                }
                //jika gagal, tampilkan pesan gagal
                else{
                    JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }catch(SQLException ex){
                //jika koneksi gagal, tampilkan pesan error
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Database",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //jika data form belum diisi sepenuhnya, tampilkan pesan error
        else{
            JOptionPane.showMessageDialog(null, "Pastikan Form Sudah Terisi Dengan Benar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxJenis;
    private javax.swing.JLabel jLabelForm;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelJenis;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelMerk;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNim;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelPlat;
    private javax.swing.JLabel jLabelTable;
    private javax.swing.JLabel jLabelTitleForm;
    private javax.swing.JLabel jLabelWarna;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNav;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JPanel jPanelWelcome;
    private javax.swing.JScrollPane jScrollPaneMobil;
    private javax.swing.JTable jTableMobil;
    private javax.swing.JTextField jTextFieldMerk;
    private javax.swing.JTextField jTextFieldPlat;
    private javax.swing.JTextField jTextFieldWarna;
    // End of variables declaration//GEN-END:variables
}
